development:
  forest_env_secret: 2ab77d0f8432d1f9237897f1da7b398c1b939fff6b90367f9934f51d4bfab31e
  forest_auth_secret: t42UVokfHlcBjpEG_WI8Tg
  forest_application_url: http://localhost:3000
  #forest_env_secret: 75cbc21dab4e764fd51b385148840e7989a094fbe9e76f11374fa6aacddf24a0
  #forest_auth_secret: Uw_4NKaCrBWv_2keYd7aYg
  #forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
  #forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  #forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  #forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
  #forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  #forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  #forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
